# Generated by Django 4.2.1 on 2023-05-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastunuid', models.CharField(max_length=200, unique=True)),
                ('dtstart', models.DateTimeField()),
                ('dtend', models.DateTimeField()),
                ('dtstamp', models.DateTimeField()),
                ('originalurl', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('categories', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('xapple_structured_location', models.CharField(max_length=255)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
