# Generated by Django 4.2.1 on 2023-05-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='wastunuid',
            new_name='uid',
        ),
    ]
