# Generated by Django 4.2.1 on 2023-05-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_wastunuid_event_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dtend',
            field=models.DateTimeField(null=True),
        ),
    ]
